name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Create .env file
        run: |
          echo "VITE_APP_FIREBASE_API_KEY=${{ secrets.VITE_APP_FIREBASE_API_KEY }}" >> .env
          echo "VITE_APP_FIREBASE_PROJECT_ID=${{ secrets.VITE_APP_FIREBASE_PROJECT_ID }}" >> .env
          echo "VITE_APP_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_APP_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "VITE_APP_FIREBASE_APP_ID=${{ secrets.VITE_APP_FIREBASE_APP_ID }}" >> .env
          echo "VITE_APP_FIREBASE_MEASUREMENTID=${{ secrets.VITE_APP_FIREBASE_MEASUREMENTID }}" >> .env
          echo "VITE_APP_FIREBASE_FCM_VAPID_KEY=${{ secrets.VITE_APP_FIREBASE_FCM_VAPID_KEY }}" >> .env
          echo "VITE_APP_AUTH_DOMAIN=${{ secrets.VITE_APP_AUTH_DOMAIN }}" >> .env
          echo "VITE_APP_DATABASE_URL=${{ secrets.VITE_APP_DATABASE_URL }}" >> .env
          echo "VITE_APP_USE_EMULATOR=true" >> .env
          echo "SKIP_PREFLIGHT_CHECK=true" >> .env
          echo "CI=false" >> .env
          echo "CYPRESS_PROJECT_ID=${{ secrets.CYPRESS_PROJECT_ID }}" >> .env
      - run: cd functions && mkdir -p private
      - name: Create cl-dev-pk.json from secret
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CODELABZ_2CD64 }}" > functions/private/cl-dev-pk.json
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - run: cd functions && npm install --legacy-peer-deps
      - run: npm install -g firebase-tools@13.10.2
      - name: Run Firebase Emulator and Start Tests
        run: firebase emulators:exec --import=./testdata --project ${{ secrets.VITE_APP_FIREBASE_PROJECT_ID }} 'npm run test'
      - uses: actions/upload-artifact@v3
        with:
          name: Cypress screenshots
          path: /home/runner/work/Codelabz/Codelabz/cypress/screenshots
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Cypress Videos
          path: /home/runner/work/Codelabz/Codelabz/cypress/videos/
